name: Feature request
description: If you feel that there is something missing, please fill out this form to let us know.
title: "[Feature]: "
labels: ["Type: Feature", "Status: Triage"]
body:
  - type: markdown
    attributes:
      value: |
        This form is for requesting new features for this module. If you experience a bug or have a question, feel free to use one of the other forms. If none of these apply to your query, you could open a blank issue as well but then it could potentially take a bit longer for anyone to get assigned to that issue.
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: Please describe the feature in as much detail as possible, preferably with a use-case example to make it clear why this feature is needed.
      placeholder: Feature description
      value: "I want to add ... to the module to help in ... scenario"
    validations:
      required: true
  - type: input
    id: tfdocs
    attributes:
      label: Terraform documentation
      description: Link to any relevant Terraform documentation
      placeholder: ex. https://registry.terraform.io/providers/hashicorp/azure/latest/docs/resources/...
    validations:
      required: false
  - type: input
    id: vendordocs
    attributes:
      label: Vendor documentation
      description: Link to any vendor specific documentation relevant for the feature
      placeholder: ex. https://docs.microsoft.com/azure/...
    validations:
      required: false
